### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by monkeyRing** [AndroidJiang/StockChart#1]
你好，哥们儿，我想问下，你的安卓版的分时图 K线图实现到哪种程度了，到你放的gif图的那种效果了吗？

**Comment by AndroidJiang** [comment]
月底前差不多发上来 现在忙着做项目中的 不方便放到测试demo  最后把整合成这个demo再发上来

**Comment by MonkeyRing** [comment]
有没有联系方式。可以向你请教请教

**Comment by MonkeyRing** [comment]
你的效果全是用 这个库实现的吗？  对于这个库的使用，有一些地方不知道怎么搞，如果方便的话，可以加我微信 502086651 QQ也是这个，我想向你请教一下，谢谢了。
