### ISSUE TITLE
线条显示问题

### ISSUE THREAD

**Issue by tiamosu** [AndroidJiang/StockChart#31]
你好，在android7.0版本中，假设成交价中有个值为Float.NaN的话，整条线会消失，均价同上，请问怎么处理呢

**Comment by AndroidJiang** [comment]
这个你都根据需求去处理，如果你那个点没有数据，那么你可以选择补齐数据，根据前面或者后面那个点赋值，第二种就是你处理绘制线条的代码，LineChartRenderer中修改

**Comment by tiamosu** [comment]
好的，多谢
