### ISSUE TITLE
Y轴横向线抖动的问题

### ISSUE THREAD

**Issue by Anayuta** [AndroidJiang/StockChart#43]
leftYAxis = combinedChart.getAxisLeft();
leftYAxis.setLabelCount(5, true);
当我把labelCount的第二个参数设置true后，滑动蜡烛图，Y轴的数字就会抖动了。请问该怎么解决.

**Comment by Anayuta** [comment]
已解决

**Comment by AndroidJiang** [comment]
可以写下解决方案   我之前遇到的抖动问题 是库本身的问题  你这个设置属性引起的 我还没遇到

**Comment by Anayuta** [comment]
我之前是  combinedChart.setAutoScaleMinMaxEnabled(true);leftYAxis.setLabelCount(5, true); 

固定了y轴横向线的条数后，后面也设置了true，图表也是自动缩放最大最小值，所以就出现横向线和Y轴的数字抖动的问题了。我的解决方案是自定义Y轴渲染，绘制label的时候 除了Y轴最大和最小，其他在中间的pos根据图表的高度和个数重新计算。横向线也是一样。
 if ((pos - labelHeight) < mViewPortHandler.contentTop()) { 
                    pos = mViewPortHandler.contentTop() + labelHeight + 3;
                } else if ((pos + labelHeight / 2) > mViewPortHandler.contentBottom()) {
                    pos = mViewPortHandler.contentBottom() - 3;
                } else { 
                    LogUtils.logd("除第一和最后一个label");
                    pos = mViewPortHandler.contentBottom() - height * (i) + labelHeight / 2;
                }

**Comment by rtyheji** [comment]
@Anayuta 在不 能加个QQ吗 有问题询问下 谢谢
