### ISSUE TITLE
关于使用ma5线作为下面的barchart和上面的蜡烛图联动

### ISSUE THREAD

**Issue by Anayuta** [AndroidJiang/StockChart#44]
当需要显示marketview的情况下，移动到的数据，展示的ma5的线在蜡烛之上，marketview将不会显示。

**Comment by AndroidJiang** [comment]
加我q说  1025065158

**Comment by Anayuta** [comment]
@AndroidJiang  有个地方我搞错了，改了下可以了。但是我这边还有个问题。当上面的蜡烛图和ma线一起的用了混合chart，下面加了个成交量的图表也用了混合chart，发现ma5的线的数据在蜡烛图的上方时，下面的图表有高亮线，但是ma5线在蜡烛下面的时候将不出现高亮线，可以帮我解释下吗？

**Comment by Anayuta** [comment]
已经解决  谢谢 AndroidJiang
